splunk/observability-workshop

- docs/detectors/index.md
Fixed to what I thought was a general description 😊
> fix description, percentile to percent

- workshop/itsi/modules/itsi_o11y_cp/scripts/install_ITSI_Content_Pack.sh
- workshop/itsi/modules/itsi_o11y_cp/vm_splunk_itsi.tf
packages in s3 bucket for easier configuration
removed local file provisionner
>  packages in s3 bucket for easier configuration

- workshop/aws/no_gdi/README.md
Still needs to be tested, and we could make a mention of this on the main page if it's useful.
> No GDI option

- content/ja/apm/docs/using-splunk-apm/example_trace.md
- content/ja/apm/docs/using-splunk-apm/service_map.md
- content/ja/apm/docs/using-splunk-apm/tag_spotlight.md
- content/ja/apm/docs/using-splunk-apm/trace_and_span.md
Fixed some image links in APM section that are incorrect.
I would really appreciate it if you could deploy this at your earliest convenience.
> fixed broken links

- content/en/imt/docs/monitoring-as-code/terraform.md
fix issue with terraform commands not executing due to updated module.
> update terraform prefix var to o11y_prefix

- workshop/aws/ec2/up
Wrong path caused error before post-installation check.
> Fix workshop aws ec2 up script.

- content/en/tko/session-5/_index.md
> Small formatting change and typos

- workshop/aws/ec2/check-instances
Fixing script(s) after changes to terraform output values
> Fixing script(s) after changes to terraform output values

- content/en/conf/opentelemetry-collector/1-installation.md
- content/en/conf/opentelemetry-collector/_index.md
In order to provide extend or stretch content for those who are more excited to get their hands dirty, I've opted to include expand sections within the workshop in order to keep with the flow of content but also let people go into further details.
I've yet to get it running on my local yet but I am keen to get feedback early while I get that set up.
I'd also advise checking that I am using the correct spelling of words due to my dyslexia / Aus spelling.
> Adding ninja section as expands to help keep with the flow of content

- content/en/conf/opentelemetry-collector/2-extensions.md
- content/en/conf/opentelemetry-collector/3-receivers.md
- content/en/conf/opentelemetry-collector/4-processors.md
- content/en/conf/opentelemetry-collector/_index.md
Revert the bindings used, I will follow up with collector practices notice later
> Reverting binding

- content/en/conf/opentelemetry-collector/3-receivers.md
Adding Ninja section on dynamic receivers.
> Include section on dynamic receivers

- content/en/conf/opentelemetry-collector/4-processors.md
I didn't want to dive too deep into connectors since that itself can be a 30m topic.
> Ninja section on connectors

- content/en/conf/opentelemetry-collector/6-service.md
Adding final ninja entry for service.
> Adding customising internal telemetry

- content/en/conf/opentelemetry-collector/2-extensions.md
- content/en/conf/opentelemetry-collector/3-receivers.md
- content/en/conf/opentelemetry-collector/5-exporters.md
- content/en/conf/opentelemetry-collector/6-service.md
Just a few typo corrections and grammatical clarifications.
> fixed a few typos and added some clarifications

- content/en/conf/opentelemetry-collector/8-develop.md
This adds the beginning section of what it would take to develop a custom component. I've currently fleshed out two of three steps to highlight best practices when starting to develop and create the skeleton of a component.
Keen to hear thoughts on how this reads and flows, before I start diving into the business logic section
> Section 8: Develop

- content/en/conf/opentelemetry-collector/8-develop.md
This is the start of the business logic section, but I feel like the ordering of the content might need to change.
> Adding business logic section

- content/en/conf/opentelemetry-collector/8-develop.md
changed the order of the development page as discussed on the sync. Will fill out business logic section tonight.
> Reordering development page

- content/en/conf/opentelemetry-collector/1-installation.md
- content/en/conf/opentelemetry-collector/8-develop.md
This is the final piece of additional technical content after I will be fixing up the minor things with formatting and update the completed code example once the GitHub project repo has been transferred across.
> Final piece of technical connect

- content/ja/other/opentelemetry-collector/1-installation/1-confirmation.md
- content/ja/other/opentelemetry-collector/2-extensions/1-health.md
- content/ja/other/opentelemetry-collector/2-extensions/3-zpages.md
- content/ja/other/opentelemetry-collector/2-extensions/_index.md
- content/ja/other/opentelemetry-collector/3-receivers/1-hostmetrics.md
- content/ja/other/opentelemetry-collector/3-receivers/2-prometheus.md
- content/ja/other/opentelemetry-collector/3-receivers/3-other-receivers.md
- content/ja/other/opentelemetry-collector/3-receivers/_index.md
- content/ja/other/opentelemetry-collector/4-processors/_index.md
- content/ja/other/opentelemetry-collector/5-exporters/_index.md
- content/ja/other/opentelemetry-collector/5-exporters/otlphttp.md
- content/ja/other/opentelemetry-collector/6-service/5-otlphttp.md
- content/ja/other/opentelemetry-collector/_index.md
Fixed typo and modified descriptions to make it easier to run the workshop. 
> Fix Otel collector JA contents

- content/en/conf24/1-zero-config-k8s/8-rum/1-rebuild-app.md
> verified rum  section to test

- content/en/conf24/1-zero-config-k8s/8-rum/1-rebuild-app.md
> more rum stuff version 2

- content/en/conf24/1-zero-config-k8s/8-rum/1-rebuild-app.md
>  polite comment

- workshop/apm/deployment.yaml
- workshop/aws/ec2/templates/userdata.yaml
Testing to see if the OTel Collector picks up MySQL
> Attempt to get OTel MySQL receiver to work

- workshop/ansible/diab-v3.yml
- workshop/ansible/orbstack.yml
- workshop/apm/deployment.yaml
- workshop/aws/ec2/templates/userdata.yaml
- workshop/petclinic/petclinic-deploy.yaml
This aligns the secrets used in in workshops and EC2 instances. Removed references to `instance` and using `env`.
> Alignment with the secrets used in Splunk Show

- content/en/workshop-setup/_index.md
This PR simply changes the workshop-setup page to make it a little clearer on environments used by Splunkers and others. More clarity is probably possible here, but at least this begins to separate what Splunkers have access to and how others can run workshops with a trial environment.
> Workshop setup updates

- layouts/partials/custom-header.html
> Fix quotes

- content/en/other/3-auto-instrumentation/3-java-microservices-k8s/10-preparation.md
- content/en/other/3-auto-instrumentation/3-java-microservices-k8s/30-auto-instrumentation.md
- content/en/other/3-auto-instrumentation/3-java-microservices-k8s/40-traces-spans-tags.md
- content/en/other/3-auto-instrumentation/3-java-microservices-k8s/50-profiling-db-query.md
- content/en/other/3-auto-instrumentation/3-java-microservices-k8s/60-log-observer-connect.md
- content/en/other/4-hpa/1-deploy-otel.md
Added section how to fix crashing otel agent pod, plus minor typo fixes
- Wrongly numbered lists
- Typos
> Minor adjustments found during Observability Ninja Workshop

- local-hosting/orbstack/start.sh.example
Error parsing zsh profile
/etc/skel/.profile:39: parse error near `\n'
- [X ] Bug fix (non-breaking change which fixes an issue)
> Connect to orb host with current user shell

- workshop/demos/optimize_enduser_experiences/OptimizeEndUserExperiences.json
Adding dashboard group for demo. No impact to workshop
> dashboard group for enduser demo

- content/en/workshop-setup/1-swipe.md
Simple change adding warning for more than 40 users in a workshop.
> add warning for large workshops

- content/en/ninja-workshops/6-lambda-kinesis/1-setup.md
- content/en/ninja-workshops/6-lambda-kinesis/2-auto-instrumentation.md
- content/en/ninja-workshops/6-lambda-kinesis/3-lambdas-in-splunk.md
- content/en/ninja-workshops/6-lambda-kinesis/4-manual-instrumentation.md
- content/en/ninja-workshops/6-lambda-kinesis/5-redeploy-lambdas.md
-  Running hugo server locally
> Lambda Tracing -- update to instructions

- content/en/ninja-workshops/8-docker-k8s-otel/5-dockerize-app.md
- content/en/ninja-workshops/8-docker-k8s-otel/6-add-instrumentation-to-dockerfile.md
- content/en/ninja-workshops/8-docker-k8s-otel/7-install-collector-k8s.md
- content/en/ninja-workshops/8-docker-k8s-otel/8-deploy-app-k8s.md
- content/en/ninja-workshops/8-docker-k8s-otel/9-customize-collector-config.md
Updated workshop docs with example outputs and tips for using vi
> Updated workshop with example outputs and tips for using vi

- content/en/ninja-workshops/8-docker-k8s-otel/6-add-instrumentation-to-dockerfile.md
- content/en/ninja-workshops/8-docker-k8s-otel/8-deploy-app-k8s.md
Added tips for Deployment.yaml and Service.yaml and made the callout about the INSTANCE more noticeable
> Added tips

- content/en/ninja-workshops/10-advanced-otel/80-sensitive-data/1-testredaction.md
- content/en/ninja-workshops/10-advanced-otel/80-sensitive-data/_index.md
> final edits to sensitive data section after manual merge

- content/en/ninja-workshops/8-docker-k8s-otel/5-dockerize-app.md
- content/en/ninja-workshops/8-docker-k8s-otel/6-add-instrumentation-to-dockerfile.md
- content/en/ninja-workshops/8-docker-k8s-otel/7-install-collector-k8s.md
- content/en/ninja-workshops/8-docker-k8s-otel/_index.md
- content/en/ninja-workshops/9-solving-problems-with-o11y-cloud/_index.md
I made a number of changes to the docker-k8s-otel workshop based on feedback from our dry run.  I also removed the hidden flag on both the docker-k8s-otel and solving-problems-with-olly workshops.
> incorporated feedback to the docker-k8s-otel workshop 

- content/en/ninja-workshops/12-alerting_monitoring_with_itsi/1-getting-started/1-access-cloud-instances.md
- content/en/ninja-workshops/12-alerting_monitoring_with_itsi/1-getting-started/_index.md
- content/en/ninja-workshops/12-alerting_monitoring_with_itsi/2-creating-basic-alerts/_index.md
- content/en/ninja-workshops/12-alerting_monitoring_with_itsi/3-creating-services-in-itsi/_index.md
- content/en/ninja-workshops/12-alerting_monitoring_with_itsi/_index.md
> Obs 122 workshop

- content/en/ninja-workshops/9-solving-problems-with-o11y-cloud/2-deploy-collector.md
Minor update to the solving-problems-with-o11y-cloud workshop
> updated solving-problems-with-o11y-cloud to clarify values.yaml changes

- content/en/ninja-workshops/3-opentelemetry-collector-workshops/2-advanced-collector/9-sum-count/9-2-sum.md
- content/en/ninja-workshops/3-opentelemetry-collector-workshops/2-advanced-collector/9-sum-count/_index.md
Added a few small updates to yaml config to help explain the connector config
> Added explanation to count and sum connectors in yaml config

- content/en/ninja-workshops/8-docker-k8s-otel/6-add-instrumentation-to-dockerfile.md
Simple fix to add sudo
In use.
> add sudo to troubleshooting step

- content/en/ninja-workshops/13-observing_business_journeys/_index.md
Creating new workshop for Observability SAs to demo and sell business journeys.
> First draft of Observing Critical Business Journeys workshop

- content/en/splunk4rookies/observability-cloud/3-quick-tour/1-homepage/1-home-page.md
Update to match new UI 
Fixes # 409
> Update English Home Page 3.1.1 screenshot and legend
